[build]
  command = "npm run build"
  publish = "dist"
  environment = {
    NODE_VERSION = "16"
    VITE_API_BASE_URL = "https://cubularpyapi-production.up.railway.app/api/v1"
    VITE_BASE_URL = "https://cubularpyapi-production.up.railway.app"
  }

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
